language: ruby

rvm:
  - 2.2.0

services:
  - redis-server

env:
  - REDIS_HOST=localhost REDIS_PORT=6379 REDIS_DB=1 REDIS_SQ_DB=6 RAILS_ENV=test DB_USERNAME=postgres

before_install:
  - sudo apt-get update
  - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get install postgresql-client-common postgresql-9.4
  - sudo service postgresql start
  - bundle install --jobs=8
  - bundle exec rake db:setup

script:
  - bundle exec rspec

notifications:
  email: false
